apiVersion: v1
kind: Deployment
metadata:
  name: mlproject
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mlproject
  template:
    metadata:
      labels:
        app: mlproject
    spec:
      containers:
      - name: mlproject
        image: 982641132963.dkr.ecr.eu-west-1.amazonaws.com/robo-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: mlproject
spec:
  type: LoadBalancer
  selector:
    app: mlproject
  ports:
    - name: https
      protocol: TCP
      port: 8080
      targetPort: 3000
  